### ISSUE TITLE
Polymer 2.0 compliance

### ISSUE THREAD

**Issue by tomberek** [platosha/rest-api#18]

**Comment by pedro2555** [comment]
Giving my best at it

**Comment by platosha** [comment]
Hey, if anyone is interested, please try the `2.0-preview` branch. All the tests pass there already.

**Comment by pedro2555** [comment]
Will do later today, thanks. I'll give some feedback up to the end of the week (I need something like this fairly quick)

**Comment by pedro2555** [comment]
2.0-preview branch seems to work fine.

I may add some features, since I can't use this with the API I'm connecting to without altering the source code slight, and I need some sort of filtering (which I'm not really sure you have at the moment).

I'll keep you posted if anything a miss under Polymer 2.0

**Comment by platosha** [comment]
Thanks for your response!

I would like to know if there is anything I could implement in a generic way to improve the API compatibility. Please provide details on any incompatibilities, if possible.

Also please note the custom transport element feature. When in use, it makes the `<rest-api>` to pass all the requests through your transport element. Thus, this allows to implement any API specific data processing, client-side filtering, and such. To use, make an element [implementing RestApi.AbstractTransportBehavior API](https://platosha.github.io/rest-api/components/rest-api/#RestApi.AbstractTransportBehavior), and place it as a child of `<rest-api>` with a `rest-api-transport` attribute.

**Comment by pedro2555** [comment]
Ha, got the transport thing, maybe this works out of the box after all then. I'll check that.

**Comment by platosha** [comment]
I’ve fixed some bugs that I’ve found with demos, then merged `2.0-preview` to `master` and tagged `v2.0.0-pre.1`. Seems to work very well at this point.

**Comment by platosha** [comment]
Alright, no issues reported, tests are green, so I’ve released v2.0.0 with hybrid P1 + P2 support. 🎉

**Comment by pedro2555** [comment]
I haven't had time, yet, to fully utilize the element (in using the features it provides over iron-ajax), but I am using it on a Polymer 2 app still and have no issues to report at this point.

Thanks.
