### ISSUE TITLE
Will it support an authentication mechanism?

### ISSUE THREAD

**Issue by leogr** [platosha/rest-api#2]
e.g. OAuth2.0?

Is it in the horizon to be added?
Thanks

**Comment by platosha** [comment]
Yes, it definitely will support authentication.

At first, I am going to add an ajax request configuration event. Then the users will be able to attach custom params / headers in each request, so that the authentication would be possible.

Will provide some examples with existing APIs, including those with the authenticated requests.

We’ll see how it can be improved afterwards.

**Comment by leogr** [comment]
Thanks for the answer!

It would be useful to add an "hook" too, because in some use cases (e.g. when you need to refresh the access token) some logic may be required when the request starts.

Currently, I'm working in a private project where we patched iron-ajax (and extended iron-form for editing) in order to do that. But we know that's not a definitive solution.
So, if you need some help let me know, I'd really like to use a component with a good design like yours.

**Comment by platosha** [comment]
Glad to hear that you’re interested in my component. Your help is welcome.

Probably, the rest-api component couldn’t be used as a replacement of iron-ajax for a while. There is another serious production use problem, apart from the authentication: possible conflicts when editing the same resource on multiple clients. No conflict prevention nor resolution is implemented.

Back to the topic. Can you share an example of this kind of a hook?

**Comment by leogr** [comment]
OT: IMHO, the component should not handle the concurrency strategy because it may vary case by case, however in an editing context could be useful to have a "update if current" strategy but I think it requires some server-side effort.

Back to the topic: the following is an early attempt to patch the ironAjax's `generateRequest()` that I'm sharing just as example (sorry for the bad code, I know that's very hack-ish, but newer code we're using it's too long and I can't share it).
Assume `apiClient` is a simple provider that handle OAuth and store session tokens, the following function replaces the ironAjax's `generateRequest()` mainly adding two features:
- add required headers by `apiClient.attachAuthorizationHeader(this.headers)`
- chain an `unauthorizedReTryHandler` to the promise, that in case of 401 it will refresh the access token by `apiClient.refreshToken()` then re-try the original request.

``` js
function (apiClient, ironAjax) {

        ironAjax._unauthorizedReTryCount = 0;
        var unauthorizedReTryHandler = function (apiClient, ironAjax, request, error) {
          if (ironAjax._unauthorizedReTryCount === 0 && request.xhr.status == 401) {
            ironAjax._unauthorizedReTryCount++;
            return apiClient.refreshToken().then(function () {
              ironAjax._unauthorizedReTryCount = 0;
              return ironAjax.generateRequest().completes;
            });
          }
          // else pass back the rejection reason
          return Promise.reject(error);
        }; // bind to promise

        // generateRequest hook
        ironAjax.generateRequest = function () {

          var request = /** @type {!IronRequestElement} */ (document.createElement('iron-request'));

          apiClient.attachAuthorizationHeader(this.headers);
          var requestOptions = this.toRequestOptions();
          this.activeRequests.push(request);

          var promise = request.completes;
          promise = promise.catch(
            unauthorizedReTryHandler.bind(promise, apiClient, ironAjax, request)
          );

          promise.then(
            this._boundHandleResponse
          ).catch(
            this._handleError.bind(this, request)
          ).then(
            this._discardRequest.bind(this, request)
          );

          request.send(requestOptions);

          this._setLastRequest(request);
          this._setLoading(true);

          this.fire('request', {
            request: request,
            options: requestOptions
          });

          return request;

        }.bind(ironAjax, this);
      }
```

**Comment by platosha** [comment]
Thanks for sharing your needs and opinion!

Will add these features.

**Comment by leogr** [comment]
The hook could be very simple to implement if `iron-ajax` would use:
`this.push('activeRequest', request);`
instead of 
`this.activeRequest.push(request)` [here](https://github.com/PolymerElements/iron-ajax/blob/bcdb5d304e0356b680fb47ef02ef922f8d2fc894/iron-ajax.html#L436)

In this way, an external component can observe when `activeRequest` changes then hooks `request` as needed.

We could file an issue to [`iron-ajax`](https://github.com/PolymerElements/iron-ajax/)... what do you think about?

**Comment by platosha** [comment]
PR to `iron-ajax` is definitely a good idea.

Not sure if this project should be tightly coupled with `iron-ajax`, though. It is used as an AJAX request library for now just for the usage simplicity. I thought of changing it to something more lightweight in future. Would prefer to implement the hook in this project in a `iron-ajax`-independent way for this reason.

**Comment by leogr** [comment]
In our project we hooked `iron-ajax` mainly because we used a custom `iron-form` to perform some API call.

I agree with you that using a `iron-ajax`-independent way could be better, however sharing just one configured `iron-ajax` with other API-related components (e.g. other 3rd parties components) looks like very interesting. 

Definitively I'm not sure which is the best choice :)

**Comment by platosha** [comment]
FYI: With the requirements from this thread in mind, I’m working on the “transports” feature.

The idea is simple. By default, `<rest-api>` uses an internal `<iron-ajax>` for making the API requests. You can add custom `<iron-ajax>`-compatible API transport elements in the light DOM of the API. They can be either defined in the API level, or scoped to the individual resource.

The transport elements are used in the following way. For every API request, the `<rest-api>` finds a transport element (the closest custom override in the resource hierarchy or the default internal `<iron-ajax>`), then assings all the request properties (`method`, `url`, `params`, `headers`, `body`) and calls `generateRequest()`.

This will allow everyone to implement a custom query/auth/fallback logic through a custom ajax element, without having to monkey-patch `<iron-ajax>`.

WIP in the `feature/transport` branch. The implementation and the tests are pretty much ready, lacking documentation and examples yet.
